// TODO: This file will be generated by scripts/generate-types.ts
// Run `npm run generate-types` to generate types from Supabase schema

export type Database = {
  public: {
    Tables: {
      // Types will be generated here based on Supabase schema
    }
    Views: {
      // View types will be generated here
    }
    Functions: {
      // Function types will be generated here
    }
  }
}
